# MIT License
#
# Copyright (c) 2026-2036 Pophu and contributors
# https://github.com/pophu/nimmake
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Ninja"""

from pathlib import Path

from nimmake.builders.base import Targets
from nimmake.configs import PARTY_LIB_PREFIX
from nimmake.thirdParties import ThirdParty
from nimmake.utils import log


class Ninja:
    def __init__(
        self,
        helper: dict[str, str],
        targets_commands: dict[str, dict],
        parties: dict[str, ThirdParty],
        target: str | Targets = "",
        targets: str | list[str] = None,
        default_target: str = "",
        phonies: str | list[str] = None,
        commands: str | list[str] = None,
        # parties: list[dict] = None,
        # flags: dict[str, list] = None,
        compile_commands: list[dict] = None,
    ):
        self.helper = helper
        self.targets_commands = targets_commands
        # self.flags = flags or {}
        self._compile_commands = compile_commands or []
        self.parties = parties or {}
        self.target = target

        self.targets = targets or []
        self.default_target = default_target
        self.phonies = phonies or []
        self.commands = commands or []
        self.target_out = ""
        self.libs_process = []
        self.libpath_process = []

        self.__party()

        self.lines: list[str] = []
        self.toolchain_lines: list[str] = []
        self.header_lines: list[str] = []
        self.flags_lines: list[str] = []
        self.rules_lines: list[str] = []
        self.objs_lines: list[str] = []
        self.links_lines: list[str] = []
        self.phonies_lines: list[str] = []
        self.commands_lines: list[str] = []

        self.ninja_cc_rule = ""
        self.ninja_cxx_rule = ""
        self.ninja_as_rule = ""
        self.ninja_ld_rule = ""
        self.ninja_ar_rule = ""

        self.flags_lines: list[str] = []
        log.debug(f"ninja: {self.target}")

        # self.__party()

    def gen(self, fpath: str | Path = "build.ninja") -> str:
        """生成 Ninja build 文件并写入磁盘

        Returns:
            生成的 Ninja 文件内容字符串
        """
        log.info("ninja  gen ...")

        # content = self._build_ninja_content()
        self.__build_ninja_content()
        content = ""
        content += "\n".join(self.header_lines)
        content += "\n"
        content += "\n".join(self.toolchain_lines)
        content += "\n"
        content += "\n".join(self.flags_lines)
        content += "\n"
        content += "\n".join(self.rules_lines)
        content += "\n"
        content += "\n".join(self.objs_lines)
        content += "\n"
        content += "\n".join(self.commands_lines)
        content += "\n"
        content += "\n".join(self.links_lines)
        content += "\n"
        content += "\n".join(self.phonies_lines)
        content += "\n"
        content += "\n".join(self.lines)
        content += "\n"

        # log.info(content)
        out = Path(fpath)
        out.write_text(content, encoding="utf-8")
        return content

    def __party(self):
        for party in self.parties.values():
            if party.build_type in ["STATIC", "SHARED"]:
                self.libs_process.append(f"{PARTY_LIB_PREFIX}{party.name.lower()}")
        if self.libs_process:
            lib_path = Path(self.helper.get("BUILDDIR", "BUILD")) / self.helper.get("LIBDIR", "LIB")
            self.libpath_process = [lib_path.as_posix()]

    def _build_ninja_header(self):
        """构建 Ninja 文件头"""
        self.header_lines.append("# ==========================================")
        self.header_lines.append("#  Auto-generated by pymakex Ninja backend")
        self.header_lines.append("# ==========================================")
        self.header_lines.append("")

        build_dir = self.helper.get("BUILDDIR", "BUILD")
        self.header_lines.append(f"builddir = {build_dir}")
        self.header_lines.append("")

    def _build_ninja_tool_chain(self):
        self.toolchain_lines.append("# ---- 工具链变量 ----")
        toolpath = Path(self.helper.get("TOOLPATH", ""))
        cc = toolpath / Path(self.helper.get("CC", "gcc"))
        cxx = toolpath / Path(self.helper.get("CXX", "g++"))
        as_ = toolpath / Path(self.helper.get("AS", "as"))
        ld = toolpath / Path(self.helper.get("LD", self.helper.get("CC", "gcc")))
        ar = toolpath / Path(self.helper.get("AR", "ar"))

        self.toolchain_lines.append(f"toolpath = {toolpath.as_posix()}")
        self.toolchain_lines.append(f"cc = {cc.as_posix()}")
        self.toolchain_lines.append(f"cxx = {cxx.as_posix()}")
        self.toolchain_lines.append(f"as = {as_.as_posix()}")
        self.toolchain_lines.append(f"ld = {ld.as_posix()}")
        self.toolchain_lines.append(f"ar = {ar.as_posix()}")
        self.toolchain_lines.append("")

    def _build_ninja_compile_flags(self):
        if not self.flags_lines:
            self.flags_lines.append("# ---- 编译标志 ----")

        _cflags = self.helper.get("CFLAGS", [])
        _cxxflags = self.helper.get("CXXFLAGS", [])
        _asflags = self.helper.get("ASFLAGS", [])
        _ldflags = self.helper.get("LINKFLAGS", [])
        _arflags = self.helper.get("ARFLAGS", ["rcs"])
        _defines = self.helper.get("DEFINES", {})
        _incpath = self.helper.get("INCPATH", [])
        _libs = self.helper.get("LIBS", [])
        _libpath = self.helper.get("LIBPATH", [])

        _libs.extend(self.libs_process)
        _libpath.extend(self.libpath_process)

        self.ninja_cc_rule = " ".join(str(f) for f in _cflags)
        self.ninja_cxx_rule = " ".join(str(f) for f in _cxxflags)
        self.ninja_as_rule = " ".join(str(f) for f in _asflags)
        self.ninja_ld_rule = " ".join(str(f) for f in _ldflags)
        self.ninja_ar_rule = " ".join(str(f) for f in _arflags)

        self.flags_lines.append(f"cflags = {self.ninja_cc_rule}")
        self.flags_lines.append(f"cxxflags = {self.ninja_cxx_rule}")
        self.flags_lines.append(f"asflags = {self.ninja_as_rule}")
        self.flags_lines.append(f"ldflags = {self.ninja_ld_rule}")
        self.flags_lines.append(f"arflags = {self.ninja_ar_rule}")

        _def_flags = []
        for k, v in _defines.items():
            if v == "":
                _def_flags.append(f"-D{k}")
            else:
                _def_flags.append(f"-D{k}={v}")
        self.flags_lines.append(f"defines = {' '.join(_def_flags)}")

        _inc_flags = [f"-I{p}" for p in _incpath]
        self.flags_lines.append(f"includes = {' '.join(_inc_flags)}")

        _lib_flags = [f"-l{l}" for l in _libs]
        _libpath_flags = [f"-L{p}" for p in _libpath]
        self.flags_lines.append(f"libs = {' '.join(_lib_flags + _libpath_flags)}")
        self.flags_lines.append("")

    def _build_ninja_party_defines_include(self):
        if not self.flags_lines:
            self.flags_lines.append("# ---- 编译标志 ----")

        for party in self.parties.values():
            name = f"_{party.name}" if party.name else ""
            defines = party.defines_flags + party.include_macros_flags
            incs = party.inc_flags
            self.flags_lines.append(f"defines{name} = {' '.join(defines)}")
            self.flags_lines.append(f"includes{name} = {' '.join(incs)}")
            self.flags_lines.append(" ")
        pass

    def _build_ninja_compile_rules(self, name: str = ""):
        if not self.rules_lines:
            self.rules_lines.append("# ---- 编译规则 ----")
        _name = f"_{name}" if name else ""
        self.rules_lines.append(f"rule cc{_name}")
        self.rules_lines.append("  depfile = $out.d")
        self.rules_lines.append(
            f"  command = $cc $cflags $defines{_name} $includes{_name} -c $in -o $out"
        )
        self.rules_lines.append("  description = CC $out")
        self.rules_lines.append("")

        self.rules_lines.append(f"rule cxx{_name}")
        self.rules_lines.append("  depfile = $out.d")
        self.rules_lines.append(
            f"  command = $cxx $cxxflags $defines{_name} $includes{_name} -c $in -o $out"
        )
        self.rules_lines.append("  description = CXX $out")
        self.rules_lines.append("")

        self.rules_lines.append(f"rule asm{_name}")
        self.rules_lines.append(f"  command = $as $asflags $includes{_name} -c $in -o $out")
        self.rules_lines.append("  description = AS $out")
        self.rules_lines.append("")

    def _build_ninja_compile_rules_byParty(self):
        for party in self.parties.values():
            self._build_ninja_compile_rules(name=party.name)
        pass

    def _build_ninja_link_rules(self):
        self.rules_lines.append("# ---- 链接规则 ----")
        self.rules_lines.append("rule link")
        self.rules_lines.append("  command = $ld $ldflags -o $out $in $libs")
        self.rules_lines.append("  description = LINK $out")
        self.rules_lines.append("")

        self.rules_lines.append("rule ar")
        self.rules_lines.append("  command = $ar $arflags $out $in")
        self.rules_lines.append("  description = AR $out")
        self.rules_lines.append("")

    def _build_ninja_compile_objs(self, name: str = ""):
        # log.info(f"targets_commands: {self.targets_commands}")
        if not self.objs_lines:
            self.objs_lines.append("# ---- 编译目标 ----")
        _all_objs: list[str] = []
        _cxx_exts = {".cpp", ".cc", ".cxx", ".c++", ".C"}
        _asm_exts = {".s", ".asm", ".S"}
        _name = f"_{name}" if name else ""

        objs = self.targets_commands.get("OBJECTS", {})
        # log.error(f"==>targets_commands: {type(objs)}  ")

        for obj, item in objs.items():
            _obj = ""
            _src = ""
            if isinstance(item, list):
                _obj = obj
                _src = item[1]
            else:
                continue

            if not _obj or not _src:
                continue
            _all_objs.append(_obj)

            _src_lower = _src.lower()
            if any(_src_lower.endswith(ext) for ext in _asm_exts):
                _rule = f"asm{_name}"
            elif any(_src_lower.endswith(ext) for ext in _cxx_exts):
                _rule = f"cxx{_name}"
            else:
                _rule = f"cc{_name}"

            self.objs_lines.append(f"build {_obj}: {_rule} {_src}")

        self.objs_lines.append("")

    def _build_ninja_compile_reflections(self, reflections: list, name: str = ""):
        # log.info(f"targets_commands: {self.targets_commands}")
        if not self.objs_lines:
            self.objs_lines.append("# ---- 编译目标 ----")
        _all_objs: list[str] = []
        _cxx_exts = {".cpp", ".cc", ".cxx", ".c++", ".C"}
        _asm_exts = {".s", ".asm", ".S"}
        _name = f"_{name}" if name else ""

        for ref in reflections:
            # print(ref)
            _obj = ref[1]
            _src = ref[0]

            if not _obj or not _src:
                continue
            _all_objs.append(_obj)

            _src_lower = _src.lower()
            if any(_src_lower.endswith(ext) for ext in _asm_exts):
                _rule = f"asm{_name}"
            elif any(_src_lower.endswith(ext) for ext in _cxx_exts):
                _rule = f"cxx{_name}"
            else:
                _rule = f"cc{_name}"

            self.objs_lines.append(f"build {_obj}: {_rule} {_src}")

        self.objs_lines.append("")

    def _build_ninja_compile_objs_byParty(self):
        for party in self.parties.values():
            log.info(f"party: {party.name} ", party.reflections)
            self._build_ninja_compile_reflections(party.reflections, party.name)
        pass

    def _build_ninja_link_objs(self):
        if not self.links_lines:
            self.links_lines.append("# ---- 链接目标 ----")
        tgts = self.targets_commands.get("TARGETS", {})
        libs = self.targets_commands.get("LIBS", {})
        self.target_out = self.target.name if self.target else ""
        if libs:
            for lib, lib_item in libs.items():
                _rule = "ar"
                self.links_lines.append(f"build {lib}: {_rule} {lib_item[1]}")
                self.links_lines.append(" ")

        # log.error(f"==>libs : {libs}  ")
        party_lib_str = ""
        for libs_ in self.libs_process:
            party_lib_str += f"{self.libpath_process[0]}/lib{libs_}.a"
            party_lib_str += " "
        if not tgts:
            return
        for tgt, tgt_item in tgts.items():
            _target = tgt
            _objs = tgt_item[1]
            _rule = "link"
            self.links_lines.append(f"build {_target}: {_rule} {_objs} {party_lib_str}  ")
            self.links_lines.append(" ")
            if self.target_out and self.target_out in _target:
                self.target_out = _target

        if self.target_out != self.helper.get("TARGET", ""):
            self.links_lines.append(f"default {self.target_out}")
            self.links_lines.append(" ")
            return

    def _build_ninja_custom_commands(self):
        if not self.commands_lines:
            self.commands_lines.append("# ---- 自定义命令 ----")
        if self.commands:
            for _cmd, _args in self.commands.items():
                arg_str = []
                # log.info(f"cmd: {_cmd}, args: {_args}")
                i = 0
                for _arg in _args.get("commands", []):
                    # arg_str.append(_arg)
                    if i > 0:
                        arg_str.append(f"       && {_arg}")
                        continue
                    arg_str.append(f"  command = {_arg} $")
                    i += 1
                self.commands_lines.append(f"build {_cmd}: phony ")
                self.commands_lines.extend(arg_str)
                # self.commands_lines.append(f"  command = {arg_str}")
                self.commands_lines.append("")
        # for line in self.commands_lines:
        #     print(line)
        # print(self.commands_lines)

    def _build_ninja_phony(self):
        if not self.phonies_lines:
            self.phonies_lines.append("# ---- 伪目标 ----")
        # _phonies = self.helper.get("PHONIES", {})
        if self.phonies_lines:
            for _pname, _pitem in self.phonies.items():
                # name = _pname
                cmd_tgt = _pitem.get("phonies", [])
                # log.output(f"pname: {_pname}, phony deps: {cmd_tgt}")
                _deps_str = ""
                for c_t in cmd_tgt:
                    if self.target and c_t == self.target.name:
                        _deps_str += f"{self.target_out}"
                        _deps_str += " "
                        continue
                    _deps_str += f"{c_t}"
                    _deps_str += " "

                self.phonies_lines.append(f"build {_pname}: phony {_deps_str}")
            self.lines.append("")

            # for _pname, _pdeps in _phonies.items():
            #     _deps_str = (
            #         " ".join(str(d) for d in _pdeps) if isinstance(_pdeps, list) else str(_pdeps)
            #     )
            #     self.lines.append(f"build {_pname}: phony {_deps_str}")
            # self.lines.append("")

    # def _build_ninja_aliases(self):
    #     self.lines.append("# ---- ALIASES ----")
    #     _aliases = self.helper.get("ALIASES", {})
    #     if _aliases:
    #         self.lines.append("# ---- ALIASES ----")
    #         for _alias, _target in _aliases.items():
    #             self.lines.append(f"alias {_alias} = {_target}")
    #             self.lines.append("")

    def __build_ninja_content(self) -> str:
        # 1. 文件头
        self._build_ninja_header()

        # 2. 工具链变量
        self._build_ninja_tool_chain()

        # 3. 编译/链接标志变量
        self._build_ninja_compile_flags()

        # 3.1 编译/链接标志变量 party
        self._build_ninja_party_defines_include()

        # 4. 编译规则
        self._build_ninja_compile_rules()

        # 4.1 party 编译规则
        self._build_ninja_compile_rules_byParty()

        # 5. 链接规则
        self._build_ninja_link_rules()

        # 6. 编译目标
        # self._build_ninja_compile_objs()

        # 6.1 party 编译目标
        self._build_ninja_compile_objs_byParty()

        # 7. 链接目标
        self._build_ninja_link_objs()

        # 8. 自定义命令
        self._build_ninja_custom_commands()

        # 9. 伪目标
        self._build_ninja_phony()

        # # 10. ALIASES
        # self._build_ninja_aliases()

        self.lines.append("\n")

        # return "\n".join(self.lines)
        pass

    def _build_ninja_content(self) -> str:
        """构建 Ninja 文件内容"""
        L: list[str] = []
        h = self.helper

        # ==================================================================
        # 1. 文件头
        # ==================================================================
        L.append("# ==========================================")
        L.append("#  Auto-generated by pymakex Ninja backend")
        L.append("# ==========================================")
        L.append("")

        L.append(f"builddir = {h.get('BUILDDIR', 'BUILD')}")
        L.append("")

        # ==================================================================
        # 2. 工具链变量
        # ==================================================================
        L.append("# ---- 工具链变量 ----")
        L.append(f"cc = {h.get('CC', 'gcc')}")
        L.append(f"cxx = {h.get('CXX', 'g++')}")
        L.append(f"as = {h.get('AS', 'as')}")
        L.append(f"ld = {h.get('LD', h.get('CC', 'gcc'))}")
        L.append(f"ar = {h.get('AR', 'ar')}")
        L.append("")

        # ==================================================================
        # 3. 编译/链接标志变量
        # ==================================================================
        L.append("# ---- 编译标志 ----")

        _cflags = h.get("CFLAGS", [])
        _cxxflags = h.get("CXXFLAGS", [])
        _asflags = h.get("ASFLAGS", [])
        _ldflags = h.get("LINKFLAGS", [])
        _arflags = h.get("ARFLAGS", ["rcs"])
        _defines = h.get("DEFINES", {})
        _incpath = h.get("INCPATH", [])
        _libs = h.get("LIBS", [])
        _libpath = h.get("LIBPATH", [])

        L.append(f"cflags = {' '.join(str(f) for f in _cflags)}")
        L.append(f"cxxflags = {' '.join(str(f) for f in _cxxflags)}")
        L.append(f"asflags = {' '.join(str(f) for f in _asflags)}")
        L.append(f"ldflags = {' '.join(str(f) for f in _ldflags)}")
        L.append(f"arflags = {' '.join(str(f) for f in _arflags)}")

        _def_flags = []
        for k, v in _defines.items():
            if v == "":
                _def_flags.append(f"-D{k}")
            else:
                _def_flags.append(f"-D{k}={v}")
        L.append(f"defines = {' '.join(_def_flags)}")

        _inc_flags = [f"-I{p}" for p in _incpath]
        L.append(f"includes = {' '.join(_inc_flags)}")

        _lib_flags = [f"-l{l}" for l in _libs]
        _libpath_flags = [f"-L{p}" for p in _libpath]
        L.append(f"libs = {' '.join(_lib_flags + _libpath_flags)}")
        L.append("")

        # ==================================================================
        # 4. 编译规则 (cc / cxx / asm)  —  带 depfile 支持
        # ==================================================================
        L.append("# ---- 编译规则 ----")

        L.append("rule cc")
        L.append("  depfile = $out.d")
        L.append("  command = $cc $cflags $defines $includes -c $in -o $out")
        L.append("  description = CC $out")
        L.append("")

        L.append("rule cxx")
        L.append("  depfile = $out.d")
        L.append("  command = $cxx $cxxflags $defines $includes -c $in -o $out")
        L.append("  description = CXX $out")
        L.append("")

        L.append("rule asm")
        L.append("  command = $as $asflags $includes -c $in -o $out")
        L.append("  description = AS $out")
        L.append("")

        # ==================================================================
        # 5. 链接规则
        # ==================================================================
        L.append("# ---- 链接规则 ----")
        L.append("rule link")
        L.append("  command = $ld $ldflags -o $out $in $libs")
        L.append("  description = LINK $out")
        L.append("")

        L.append("rule ar")
        L.append("  command = $ar $arflags $out $in")
        L.append("  description = AR $out")
        L.append("")

        # ==================================================================
        # 6. 编译目标 — 逐个源文件生成 build 语句
        # ==================================================================
        L.append("# ---- 编译目标 ----")
        _all_objs: list[str] = []
        _cxx_exts = {".cpp", ".cc", ".cxx", ".c++", ".C"}
        _asm_exts = {".s", ".asm", ".S"}

        for _cmd in self._compile_commands:
            if isinstance(_cmd, dict):
                _obj = _cmd.get("obj", [""])[0] if _cmd.get("obj") else ""
                _src = _cmd.get("src", [""])[0] if _cmd.get("src") else ""
            elif isinstance(_cmd, list | tuple) and len(_cmd) >= 3:
                _obj = str(_cmd[1])
                _src = str(_cmd[2])
            else:
                continue

            if not _obj or not _src:
                continue
            _all_objs.append(_obj)

            _src_lower = _src.lower()
            if any(_src_lower.endswith(ext) for ext in _asm_exts):
                _rule = "asm"
            elif any(_src_lower.endswith(ext) for ext in _cxx_exts):
                _rule = "cxx"
            else:
                _rule = "cc"

            L.append(f"build {_obj}: {_rule} {_src}")
        L.append("")

        # ==================================================================
        # 7. 链接目标
        # ==================================================================
        if self.targets_commands:
            L.append("# ---- 链接目标 ----")
            _tgt = self.targets_commands
            _target = _tgt.get("target", [""])[0]
            _objs = _tgt.get("obj", [])
            _tgt_libs = _tgt.get("libs", [])
            _tgt_libpathes = _tgt.get("libpathes", [])
            _tgt_toolflags = _tgt.get("toolflags", [])

            _objs_str = " ".join(str(o) for o in _objs)
            _extra_libs = " ".join(str(l) for l in _tgt_libs + _tgt_libpathes)

            L.append(f"build {_target}: link {_objs_str}")
            if _extra_libs:
                L.append(f"  libs = $libs {_extra_libs}")
            if _tgt_toolflags:
                L.append(f"  ldflags = $ldflags {' '.join(str(f) for f in _tgt_toolflags)}")
            L.append("")

            L.append("# ---- 默认目标 ----")
            L.append(f"default {_target}")
            L.append("")

        # ==================================================================
        # 8. 自定义命令 (COMMANDS)
        # ==================================================================
        _commands = h.get("COMMANDS", {})
        if _commands:
            L.append("# ---- 自定义命令 ----")
            for _name, _cmd_lines in _commands.items():
                _rule_name = f"cmd_{_name}"
                L.append(f"rule {_rule_name}")
                if isinstance(_cmd_lines, list):
                    L.append(f"  command = {' && '.join(str(c) for c in _cmd_lines)}")
                else:
                    L.append(f"  command = {_cmd_lines}")
                L.append(f"  description = CMD {_name}")
                L.append("")
                L.append(f"build {_name}: {_rule_name}")
                L.append("")

        # ==================================================================
        # 9. 伪目标 (PHONIES)
        # ==================================================================
        _phonies = h.get("PHONIES", {})
        if _phonies:
            L.append("# ---- 伪目标 ----")
            for _pname, _pdeps in _phonies.items():
                _deps_str = (
                    " ".join(str(d) for d in _pdeps) if isinstance(_pdeps, list) else str(_pdeps)
                )
                L.append(f"build {_pname}: phony {_deps_str}")
            L.append("")

        # ==================================================================
        # 10. 别名 (ALIASES)
        # ==================================================================
        _aliases = h.get("ALIASES", {})
        if _aliases:
            L.append("# ---- 别名目标 ----")
            for _aname, _adeps in _aliases.items():
                _deps_str = (
                    " ".join(str(d) for d in _adeps) if isinstance(_adeps, list) else str(_adeps)
                )
                L.append(f"build {_aname}: phony {_deps_str}")
            L.append("")

        return "\n".join(L)


"""
思路
方案一：Per-file 变量覆盖
# HAL 库 — 关闭警告，带上 HAL 专用宏
build BUILD/OBJ/DRIVER/stm32f4xx_hal.o: cc src_stm/Drivers/.../stm32f4xx_hal.c
  cflags = $cflags -w
  defines = $defines -DSTM32F407xx -DUSE_HAL_DRIVER

# 应用代码 — 无额外覆盖，直接用全局变量
build BUILD/OBJ/CORE/main.o: cc src_stm/Core/Src/main.c


方案二：多 rule 定义（按来源分组）

hal_cflags = $cflags_base -w
hal_defines = -DSTM32F407xx -DUSE_HAL_DRIVER
app_cflags = $cflags_base -Wall -Wextra

rule cc_hal
  command = $cc $hal_cflags $hal_defines $hal_includes -c $in -o $out

rule cc_app
  command = $cc $app_cflags $defines $app_includes -c $in -o $out

build BUILD/OBJ/DRIVER/stm32f4xx_hal.o: cc_hal src_stm/Drivers/.../stm32f4xx_hal.c
build BUILD/OBJ/CORE/main.o: cc_app src_stm/Core/Src/main.c


方案三 subninja 拆分
subninja src_stm/Core/build.ninja
subninja src_stm/Drivers/build.ninja
subninja thirdparty/FreeRTOS/build.ninja

build clean: phony
  command = rm -rf obj app \
            && rm -rf *.d .ninja_deps .ninja_log \
            && echo "清理完成"
"""
